version: '3'

services:
  dejavu:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./samples/dejavu.cnf:/dejavu/dejavu.cnf:ro
      - ./samples/moh:/dejavu/moh:ro
    links:
      - mysql

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=somepassword
      - MYSQL_USER=dejavu
      - MYSQL_PASSWORD=dejavu
      - MYSQL_DATABASE=dejavu
